export const COMMON_ROLES = [
  "Administrador(a)",
  "Advogado(a)",
  "Analista Administrativo",
  "Analista Comercial",
  "Analista de Atendimento",
  "Analista de Banco de Dados",
  "Analista de Cobrança",
  "Analista de Compras",
  "Analista de Comunicação",
  "Analista de Contabilidade",
  "Analista de Controle de Qualidade",
  "Analista de Customer Success",
  "Analista de Dados",
  "Analista de Departamento Pessoal",
  "Analista de E-commerce",
  "Analista de Engenharia",
  "Analista de Estoque",
  "Analista de Faturamento",
  "Analista de Finanças",
  "Analista de Importação e Exportação",
  "Analista de Infraestrutura",
  "Analista de Logística",
  "Analista de Marketing",
  "Analista de Mídias Sociais",
  "Analista de Negócios",
  "Analista de Operações",
  "Analista de Planejamento",
  "Analista de Produto",
  "Analista de Projetos",
  "Analista de Qualidade",
  "Analista de Recursos Humanos",
  "Analista de Redes",
  "Analista de Risco",
  "Analista de Segurança da Informação",
  "Analista de SEO",
  "Analista de Sistemas",
  "Analista de Suporte",
  "Analista de Testes (QA)",
  "Analista de Vendas",
  "Arquiteto(a)",
  "Arquiteto(a) de Software",
  "Assistente Administrativo",
  "Assistente Comercial",
  "Assistente de Departamento Pessoal",
  "Assistente de Logística",
  "Assistente de Marketing",
  "Assistente de Recursos Humanos",
  "Assistente Financeiro",
  "Atendente",
  "Auditor(a)",
  "Auxiliar Administrativo",
  "Auxiliar de Almoxarifado",
  "Auxiliar de Compras",
  "Auxiliar de Cozinha",
  "Auxiliar de Enfermagem",
  "Auxiliar de Escritório",
  "Auxiliar de Estoque",
  "Auxiliar de Limpeza",
  "Auxiliar de Logística",
  "Auxiliar de Manutenção",
  "Auxiliar de Operações",
  "Auxiliar de Produção",
  "Auxiliar de Serviços Gerais",
  "Auxiliar Financeiro",
  "Balconista",
  "Biomédico(a)",
  "Caixa",
  "Comprador(a)",
  "Consultor(a)",
  "Consultor(a) Comercial",
  "Consultor(a) de Vendas",
  "Consultor(a) Financeiro",
  "Contador(a)",
  "Coordenador(a) Administrativo",
  "Coordenador(a) Comercial",
  "Coordenador(a) de Logística",
  "Coordenador(a) de Marketing",
  "Coordenador(a) de Recursos Humanos",
  "Coordenador(a) de Vendas",
  "Coordenador(a) Financeiro",
  "Corretor(a) de Imóveis",
  "Designer",
  "Designer Gráfico",
  "Designer UI/UX",
  "Desenvolvedor(a) Back-end",
  "Desenvolvedor(a) Front-end",
  "Desenvolvedor(a) Full Stack",
  "Desenvolvedor(a) Mobile",
  "Desenvolvedor(a) de Software",
  "Diretor(a) Comercial",
  "Diretor(a) de Marketing",
  "Diretor(a) de Operações",
  "Diretor(a) Financeiro",
  "Eletricista",
  "Enfermeiro(a)",
  "Engenheiro(a) Civil",
  "Engenheiro(a) de Computação",
  "Engenheiro(a) de Dados",
  "Engenheiro(a) de Produção",
  "Engenheiro(a) de Software",
  "Engenheiro(a) Eletricista",
  "Engenheiro(a) Mecânico",
  "Especialista de Produto",
  "Especialista em Marketing",
  "Estagiário(a)",
  "Farmacêutico(a)",
  "Fisioterapeuta",
  "Frentista",
  "Gerente Administrativo",
  "Gerente Comercial",
  "Gerente de Contas",
  "Gerente de E-commerce",
  "Gerente de Loja",
  "Gerente de Logística",
  "Gerente de Marketing",
  "Gerente de Operações",
  "Gerente de Produto (PM)",
  "Gerente de Projetos",
  "Gerente de Recursos Humanos",
  "Gerente de Tecnologia (TI)",
  "Gerente de Vendas",
  "Gerente Financeiro",
  "Gestor(a) de Tráfego",
  "Jovem Aprendiz",
  "Líder Técnico (Tech Lead)",
  "Mecânico",
  "Médico(a)",
  "Motorista",
  "Nutricionista",
  "Odontologista",
  "Operador(a) de Caixa",
  "Operador(a) de Call Center",
  "Operador(a) de Empilhadeira",
  "Operador(a) de Logística",
  "Operador(a) de Máquinas",
  "Operador(a) de Produção",
  "Operador(a) de Telemarketing",
  "Pedagogo(a)",
  "Pedreiro",
  "Porteiro",
  "Professor(a)",
  "Programador(a)",
  "Promotor(a) de Vendas",
  "Psicólogo(a)",
  "Recepcionista",
  "Recrutador(a)",
  "Redator(a)",
  "Representante Comercial",
  "Secretária(o)",
  "Segurança",
  "Supervisor(a)",
  "Supervisor(a) Comercial",
  "Supervisor(a) de Logística",
  "Supervisor(a) de Operações",
  "Supervisor(a) de Produção",
  "Supervisor(a) de Vendas",
  "Técnico(a) Administrativo",
  "Técnico(a) de Enfermagem",
  "Técnico(a) de Informática",
  "Técnico(a) de Manutenção",
  "Técnico(a) de Segurança do Trabalho",
  "Técnico(a) de Suporte",
  "Técnico(a) em Edificações",
  "Técnico(a) em Eletrônica",
  "Vendedor(a)",
  "Vendedor(a) Externo",
  "Vendedor(a) Interno",
  "Veterinário(a)",
  "Web Designer"
];
